### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by ssqiao** [hyliang96/CSGCNN#1]
Hi! Nice work. I'm very concerned about when will you release the source codes?  I can't wait to reproduce those interesting results.

**Comment by Vickeyhw** [comment]
I'm looking forward to the source codes too, especially what value should be set to loss weight hyperparameter as well as regularization parameter g. how  to initialize CSG matrix?

**Comment by hubin111** [comment]
Hello, your work is very attractive. I hope to get your source code and reproduce the amazing results in your paper. Hope to reply  soon.

**Comment by Cheriachan** [comment]
Hello! I am looking for the source code too. Awaiting the code release

**Comment by oyzh888** [comment]
Within this week I think! And the code is under intensive construction :)
Sorry for this long wait. Because covid-19, our work is delayed.

**Comment by Cheriachan** [comment]
Thank you :)

**Comment by abhinavkaul95** [comment]
Hi guys, your work seems attractive and the results you have got is quite promising. Could you please upload the source code quickly? Need to reference your paper in a forthcoming presentation.

Even if the code is not end-to-end tested, that would work. Just need to go through the flow you guys have done so as to collaborate or even update the code or corresponding issues. Just one happy-happy scenario would work.

**Comment by hyliang96** [comment]
Hi everybody, our code for VOCPart dataset have been released now. Thanks for waiting.
